@Auto_Test6
Feature: Auto_Test6


  @Payment_Overseas_Transfer_MCY_Auth_USD-USD_SIT-1
  Scenario:Positive process of overseas transfer Bic Is DBS(USD--USD)(SIT_MCY_Auth)-1
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |Currency|
      |1102 0931 868 |OUR                      |USD     |
    And I choose the payment currency
      |Currency   |
      |USD        |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0VEC     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    Then I will compare all the data on FX Payment MX Message
      |WordPath              |
      |Bic is DBS USD-USD MCY|
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When Click My Task to find data for authorization
    When Vkey authorization for Payment transactions in the SIT environment
    Then I wait a mount
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS USD-USD|Bic is DBS USD-USD|



  @Payment_Overseas_Transfer_MCY_Auth_EUR-EUR_SIT-2
  Scenario:Positive process of overseas transfer Bic Is DBS(EUR--EUR)(SIT_MCY_Auth)-2
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitmentEUR
      |Account Number|Payment Mode for Charges |Currency|
      |1102 0931 868 |OUR                      |EUR     |
    And I choose the payment currency
      |Currency   |
      |EUR        |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0VEC     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    Then I will compare all the data on FX Payment MX Message
      |WordPath              |
      |Bic is DBS USD-USD MCY|
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When Click My Task to find data for authorization
    When Vkey authorization for Payment transactions in the SIT environment
    Then I wait a mount
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS USD-USD|Bic is DBS USD-USD|



  @Payment_Overseas_Transfer_MCY_Auth_CNY-CNY_SIT-5
  Scenario:Positive process of overseas transfer Bic Is DBS(CNY--CNY)(SIT_MCY_Auth)-3
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitmentCNY
      |Account Number|Payment Mode for Charges |Currency|
      |1102 0931 868 |OUR                      |CNY     |
    And I choose the payment currency
      |Currency   |
      |CNY        |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0VEC     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    Then I will compare all the data on FX Payment MX Message
      |WordPath              |
      |Bic is DBS USD-USD MCY|
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When Click My Task to find data for authorization
    When Vkey authorization for Payment transactions in the SIT environment
    Then I wait a mount
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS USD-USD|Bic is DBS USD-USD|



  @Payment_Overseas_Transfer_MCY_Auth_HKD-HKD_SIT-4
  Scenario:Positive process of overseas transfer Bic Is DBS(HKD--HKD)(SIT_MCY_Auth)-4
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitmentHKD
      |Account Number|Payment Mode for Charges |Currency|
      |1102 0931 868 |OUR                      |HKD     |
    And I choose the payment currency
      |Currency   |
      |HKD        |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0VEC     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    Then I will compare all the data on FX Payment MX Message
      |WordPath              |
      |Bic is DBS USD-USD MCY|
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When Click My Task to find data for authorization
    When Vkey authorization for Payment transactions in the SIT environment
    Then I wait a mount
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS USD-USD|Bic is DBS USD-USD|