@T24Payments
Feature: T24 Payment transaction

  @FxPayment
  Scenario:FX Payment Data Mapping Positive process of overseas transfer(SGD--USD)
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |selectAccount|payeeCurrency|enterAmount|expense                                  |
      |1101 0000 438|SGD          |87.09         |The expenses shall be borne by each party|
    And I choose the payment currency
      |selectAccBth|
      |USD         |
    When I enter the payee information
      |sendPaymentAccount|namePayee|
      |11010000489       |lucky    |
    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |collectingBank|
      |GL            |
    When I choose the recipient country
      |payeeAdd |payeeCountries|remittancePostscriptContent|
      |countries|UNITED STATES |ok                         |
    When I choose the nature of payment
      |selectPaymentAttributeCd|
      |Commission              |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
    |search content           |windows Title        |
    |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
    |windows Title                            |
    |Pending and Processed Payments - SIT GLDB|
    Then I do field mapping for Channel and T24 in FX Payment
    When I compare the amount is normal
    When I compare the data generated by Outgoing Message is correct
    When I type FOREX in the search box
    |search content|
    |FOREX         |
    When Use "netSilverEnv_Kevin_T24_SIT_Auth" to log in to T24 SIT environment
    When I enter the Unauthorized Forex Deals Menu page to authorize the operation

  @FxPaymentUSDToSGD
  Scenario:FX Payment Data Mapping Positive process of overseas transfer(SGD--USD)
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |selectAccount|payeeCurrency|enterAmount   |expense                                  |
      |1101 0000 489|USD          |37.81         |The expenses shall be borne by each party|
    And I choose the payment currency
      |selectAccBth|
      |SGD         |
    When I enter the payee information
      |sendPaymentAccount|namePayee|
      |11010000438       |lucky    |
    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |collectingBank|
      |GL            |
    When I choose the recipient country
      |payeeAdd |payeeCountries|remittancePostscriptContent|
      |countries|UNITED STATES |ok                         |
    When I choose the nature of payment
      |selectPaymentAttributeCd|
      |Commission              |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
      |search content           |windows Title        |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
      |windows Title                            |
      |Pending and Processed Payments - SIT GLDB|
    Then I do field mapping for Channel and T24 in FX Payment
    When I compare the amount is normal
    When I compare the data generated by Outgoing Message is correct
    When I type FOREX in the search box
      |search content|
      |FOREX         |
    When Use "netSilverEnv_Kevin_T24_SIT_Auth" to log in to T24 SIT environment
    When I enter the Unauthorized Forex Deals Menu page to authorize the operation

  @FxPaymentSGDToSGD
  Scenario:FX Payment Data Mapping Positive process of overseas transfer(SGD--USD)
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |selectAccount|payeeCurrency|enterAmount   |expense                                  |
      |1101 0000 438|SGD          |17.98        |The expenses shall be borne by each party |
    And I choose the payment currency
      |selectAccBth|
      |SGD         |
    When I enter the payee information
      |sendPaymentAccount|namePayee|
      |11010000470       |lucky    |
    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |collectingBank|
      |GL            |
    When I choose the recipient country
      |payeeAdd |payeeCountries|remittancePostscriptContent|
      |countries|UNITED STATES |ok                         |
    When I choose the nature of payment
      |selectPaymentAttributeCd|
      |Commission              |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
      |search content           |windows Title        |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
      |windows Title                            |
      |Pending and Processed Payments - SIT GLDB|
    Then I do field mapping for Channel and T24 in same currency
    When I compare the amount is normal
    When I compare the data generated by Outgoing Message is correct

  @FxPaymentUSDToUSD
  Scenario:FX Payment Data Mapping Positive process of overseas transfer(SGD--USD)
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |selectAccount|payeeCurrency|enterAmount   |expense                                  |
      |1101 0000 489|USD          |17.98        |The expenses shall be borne by each party |
    And I choose the payment currency
      |selectAccBth|
      |USD         |
    When I enter the payee information
      |sendPaymentAccount|namePayee|
      |11010000608       |lucky    |
    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |collectingBank|
      |GL            |
    When I choose the recipient country
      |payeeAdd |payeeCountries|remittancePostscriptContent|
      |countries|UNITED STATES |ok                         |
    When I choose the nature of payment
      |selectPaymentAttributeCd|
      |Commission              |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
      |search content           |windows Title        |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
      |windows Title                            |
      |Pending and Processed Payments - SIT GLDB|
    Then I do field mapping for Channel and T24 in same currency
    When I compare the amount is normal
    When I compare the data generated by Outgoing Message is correct

  @localPaymentSGDToSGD
  Scenario:Local Payment Data Mapping
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I will complete the inter-bank transfer on the page
      |rollOutAccount  |intoAccount  |amount  |
      |1101 0000 438   |1101 0000 470|18.41   |
    Then I check to see if the page jumps
    When I verify the page information and click the Next button
    Then My account has been transferred successfully
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
      |search content           |windows Title        |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I jump to the home page and enter FUNDS.TRANSFER for data mapping
      |search content|
      |FUNDS.TRANSFER|
    Then I will map the page data

  @localPaymentUSDToUSD
  Scenario:Local Payment Data Mapping
    Given logon "netSilverEnv_Kevin_SIT" in SIT environment and bypass Vkey
    When I will complete the inter-bank transfer on the page
      |rollOutAccount  |intoAccount  |amount  |
      |1101 0000 489   |1101 0000 608|18.41   |
    Then I check to see if the page jumps
    When I verify the page information and click the Next button
    Then My account has been transferred successfully
    Given Use "netSilverEnv_Kevin_T24_SIT" to log in to T24 SIT environment
    When I type in the content and click the search button
      |search content           |windows Title        |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|
    When I jump to the home page and enter FUNDS.TRANSFER for data mapping
      |search content|
      |FUNDS.TRANSFER|
    Then I will map the page data