@payment_D
  Feature:payment_D


    @Payment_Overseas_Transfer_SGD-USD_SIT——001
    Scenario:FX Payment Data Mapping Positive process of overseas transfer Bic is DBS SINGAPORE(SGD->USD)_SIT-001
      Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
      When I click on overseas transfer payment and select the account
      When I select the payment account, enter the payment currency and the payment amount and the cost commitment
        |Account Number|Payment Mode for Charges |
        |1101 000 471  |OUR                      |
      And I choose the payment currency
        |Currency|
        |USD     |
      When I enter the payee information
        |Payee's Account Number|Payee's Name|
        |667812798             |lucky       |
#    When I click on the receiving bank drop down box
      When I choose the receiving bank
        |Beneficiary Bank|
        |DBSSSGS0DOD     |
      When I choose the recipient country
        |Payee's Address |Payee's Country|Comments For Payee|
        |countries       |UNITED STATES  |ok                |
      When I choose the nature of payment
        |Purpose of Transfer|
        |Commission         |
      When I choose to submit the transfer information
      When Vkey authorization for Payment transactions in the SIT environment
      Then I will compare all the data on FX Payment
        |WordPath          |
        |Bic is DBS SGD-USD|
      Given to verify transaction in T24 using "T24-automation-SIT-login"
      When I type in the content and click the search button
        |search content           |windows Title        |WordPath          |
        |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-USD|
      When I expand the User Menu menu on the page
      When I expand the User Payments menu on the page
      When I expand the Payment Hub menu on the page
      When I expand the Payment Inquiries and Exceptions menu on the page
      When I expand the Payments Enquiry Transaction wise menu on the page
      When I jump to a newly opened page
        |windows Title                            |WordPath          |
        |Pending and Processed Payments - UAT GLDB|Bic is DBS SGD-USD|
      Then I do field mapping for Channel and T24 in FX Payment
        |WordPath          |
        |Bic is DBS SGD-USD|
      When I compare the amount is normal
        |WordPath          |
        |Bic is DBS SGD-USD|
      When I compare the data generated by Outgoing Message is correct
        |WordPath          |Name              |
        |Bic is DBS SGD-USD|Bic is DBS SGD-USD|



    @Payment_Overseas_Transfer_SGD-USD_SIT——002
    Scenario:FX Payment Data Mapping Positive process of overseas transfer Bic is DBS SINGAPORE(SGD->USD)_SIT-002
      Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
      When I click on overseas transfer payment and select the account
      When I select the payment account, enter the payment currency and the payment amount and the cost commitment
        |Account Number|Payment Mode for Charges |
        |1101 000 471  |SHA                      |
      And I choose the payment currency
        |Currency|
        |USD     |
      When I enter the payee information
        |Payee's Account Number|Payee's Name|
        |667812798             |lucky       |
#    When I click on the receiving bank drop down box
      When I choose the receiving bank
        |Beneficiary Bank|
        |DBSSSGS0DOD     |
      When I choose the recipient country
        |Payee's Address |Payee's Country|Comments For Payee|
        |countries       |UNITED STATES  |ok                |
      When I choose the nature of payment
        |Purpose of Transfer|
        |Commission         |
      When I choose to submit the transfer information
      When Vkey authorization for Payment transactions in the SIT environment
      Then I will compare all the data on FX Payment
        |WordPath          |
        |Bic is DBS SGD-USD|
      Given to verify transaction in T24 using "T24-automation-SIT-login"
      When I type in the content and click the search button
        |search content           |windows Title        |WordPath          |
        |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-USD|
      When I expand the User Menu menu on the page
      When I expand the User Payments menu on the page
      When I expand the Payment Hub menu on the page
      When I expand the Payment Inquiries and Exceptions menu on the page
      When I expand the Payments Enquiry Transaction wise menu on the page
      When I jump to a newly opened page
        |windows Title                            |WordPath          |
        |Pending and Processed Payments - UAT GLDB|Bic is DBS SGD-USD|
      Then I do field mapping for Channel and T24 in FX Payment
        |WordPath          |
        |Bic is DBS SGD-USD|
      When I compare the amount is normal
        |WordPath          |
        |Bic is DBS SGD-USD|
      When I compare the data generated by Outgoing Message is correct
        |WordPath          |Name              |
        |Bic is DBS SGD-USD|Bic is DBS SGD-USD|

    @Payment_OE_Outgoing_Bank_Transfer_USD-USD_UAT_Amount<threshold——003
    Scenario:Payment_OE_Outgoing_Bank_Transfer_(USD-USD)_UAT Amount<250K——003
      Given Use "T24-automation-UAT-login" to login to T24 environment
      When I click Outgoing ISO Bank Transfer
      Then I enter Outgoing ISO Bank Transfer Page
      When I Input incomplete information USD on Outgoing ISO Bank Transfer Page
        |Instructed Agent BIC|Transaction Currency|Transaction Amount|Debit Account Number|Creditor Bic|
        |CITIUS30            |USD                 |10001             |USD142000001        |DBSSSGS0    |
      When I Input Sender's Reference on Outgoing ISO Bank Transfer Page
        |Sender Reference|End To End Identification|
        |                |                         |
      Then I get OENumber
      Then I click pre-submit button
      When I click Accept Overrides
      Then Assert Result whether Successful
      And I close driver
      Given Use "T24-automation-UAT-login-Auth" to login to T24 environment
      When I entered the Pending Authorise Payments page
      Then I input OE Number and click Find Authorise
      Then Assert Result whether Successful
      And I close driver
      Given Use "T24-automation-UAT-login-Auth2" to login to T24 environment
      When I entered the Pending Authorise Payments page
      Then I input OE Number and click Find Authorise
      Then Assert Result whether Successful
      And I close driver
      Given Use "T24-automation-UAT-login" to login to T24 environment
      When I enter the Payments Enquiry - Transaction wise page
      Then I input FTNumber and click Find
      When I Assert enter View Page to OE Outgoing_Bank_Transfer
      Then I Assert enter View Details Page