@Sanity_Pack_INB_SIT

Feature: Sanity Pack INB SIT Test Case
  @sanity_pack_Overseas_Fund_Transfer_SGD_USD_SIT
 #境外转账
  Scenario:Overseas fund transfer SGD-USD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges|
      |1101 0002 414 |SHA                     |
    And I choose the payment currency
      |Currency|
      |USD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
      |WordPath           |
      |Bic is DBS SGD-USD |
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button
      |search content           |windows Title        |WordPath           |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-USD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
      |windows Title                            |WordPath           |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS SGD-USD |
    Then I do field mapping for Channel and T24 in FX Payment
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I compare the amount is normal
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I compare the data generated by Outgoing Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-USD|Bic is DBS SGD-USD|
    When I type FOREX in the search box use to authorize the operation
      |search content|user Authorize                 |Name              |
      |FOREX         |T24-automation-SIT-login-Auth  |Bic is DBS SGD-USD|
    When I view the exchange rate in the Payment Order RFQ Rate Audit menu On Oversea Payment MX
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS SGD-USD |

  @sanity_pack_Overseas_Fund_Transfer_USD_SGD_SIT
  Scenario:Overseas fund transfer USD-SGD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0000 489 |SHA                      |
    And I choose the payment currency
      |Currency|
      |SGD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment Different Currency MX Message
      |WordPath          |
      |Bic is DBS USD-SGD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Different Currency
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-SGD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page for Different Currency
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-SGD|
    Then I do field mapping for Channel and T24 in FX Payment for Different Currency
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I compare the amount is normal for Different Currency
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I compare the data generated by Outgoing Message is correct for Different Currency
      |WordPath          |Name              |
      |Bic is DBS USD-SGD|Bic is DBS USD-SGD|
    When I type FOREX in the search box use to authorize the operation for Different Currency
      |search content|user Authorize                 |Name              |
      |FOREX         |T24-automation-SIT-login-Auth  |Bic is DBS USD-SGD|
    When I view the exchange rate in the Payment Order RFQ Rate Audit menu On Oversea Payment MX
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS USD-SGD |

  @sanity_pack_Overseas_Fund_Transfer_SGD_SGD_SIT
  Scenario:Overseas fund transfer SGD-SGD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0002 414 |SHA                      |
    And I choose the payment currency
      |Currency|
      |SGD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment MX Message
      |WordPath          |
      |Bic is DBS SGD-SGD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-SGD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS SGD-SGD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS SGD-SGD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS SGD-SGD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-SGD|Bic is DBS SGD-SGD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS SGD-SGD |

  @sanity_pack_Overseas_Fund_Transfer_USD_USD_SIT
  Scenario:Overseas fund transfer USD-USD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0000 489 |SHA                      |
    And I choose the payment currency
      |Currency|
      |USD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment MX Message
      |WordPath          |
      |Bic is DBS USD-USD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-SGD|Bic is DBS USD-USD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS USD-USD |

    #FAST转账方式，新币转新币正流程（无授权通过）预约转账
  @sanity_pack_Local_Fund_Transfers_Fast_Appointment_Transfer_SIT
  Scenario:FAST transfer method, SGD to SGD positive process (unauthorized transfer)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Fast         |No                |Weekly   |

    #FAST转账方式，新币转新币正流程（无授权通过）周期转账
  @sanity_pack_Local_Fund_Transfers_Fast_Periodic_Transfer_SIT
  Scenario:FAST transfer method, where the SGD is transferred to the SGD in a positive process (without authorization).
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Fast         |Yes               |Weekly   |

  @sanity_pack_Local_Fund_Transfers_Fast_SGD_SGD_SIT
    #FAST转账方式，新币转新币正流程（无授权通过）
  Scenario:FAST transfer method, SGD to SGD positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|Fast         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_Fast_SGD_SGD_Choose_GLDB_SIT
    #FAST转账方式，新币转新币正流程（无授权通过）选择绿联银行
  Scenario:FAST transfer method, the SGD to SGD positive process (without authorization) choose GLDB Bank
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name                      |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |GREEN LINK DIGITAL BANK PTE LTD|Fast         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_MEPS_SGD_SGD_Appointment_Transfer_SIT
    #MEPS转账方式，新币转新币正流程（无授权通过）预约转账
  Scenario:MEPS transfer method, SGD to SGD positive process (unauthorized transfer)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Meps         |No                |Weekly   |

  @sanity_pack_Local_Fund_Transfers_MEPS_SGD_SGD_Periodic_Transfer_SIT
    #MEPS转账方式，新币转新币正流程（无授权通过）周期转账
  Scenario:MEPS transfer method, where the SGD is transferred to the SGD in a positive process (without authorization).
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Meps         |Yes               |Weekly   |

  @sanity_pack_Local_Fund_Transfers_MEPS_SGD_SGD_SIT
    #MEPS转账方式，新币转新币正流程（无授权通过）
  Scenario:MEPS transfer method, SGD to SGD positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|Meps         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_UEN_SGD_SGD_SIT
    #UEN, 新币转新币正流程（无授权通过）
  Scenario:UEN the process of converting SGD to SGD (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |UEN          |UEN123321001  |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_VPA_SGD_SGD_SIT
    #VPA 新币转新币正流程（无授权通过）
  Scenario:VPA the process of converting SGD to SGD (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content         |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |VPA          |UEN12345678901DD#GRAB  |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_Mobile_SGD_SGD_SIT
    #Mobile 新币转新币正流程（无授权通过）
  Scenario:Mobile the process of converting SGD to SGD (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |Mobile       |90688461       |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  @sanity_pack_Local_Fund_Transfers_NRIC/FIN_SGD_SGD_SIT
    #NRIC/FIN 新币转新币正流程（无授权通过）
  Scenario:NRIC the process of converting SGD to SGD (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |NRIC         |S1234569B      |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

     #本人互转交易正常
  @sanity_pack_Transfers_Within_My_Green_Link_Accounts_SGD_SGD_SIT
  Scenario:Local Payment Data Mapping FX Payment (SGD->SGD)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I fill in the transfer information on the page
      |From Account |To Account   |
      |11010002414  |11010002430  |
    Then I checked the transfer success in My transactions

    @sanity_pack_Fixed_Deposit_One_Month_SIT
# SGD单币种账户买入1个月不转存定期正流程（无授权）
  Scenario:SGD single-currency account is purchased for one month, and it is not transferred to regular positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits menu
    Then I fill in the information about the SGD transfer on the time deposit page
      |Transfer accounts   |Into account|Amount |Period  |Transfer accounts way|
      |1101 0000 470       |11010000438 |250000 |1 Month |1                    |
    Given to verify transaction in T24 using "T24-automation-SIT-login"

  @sanity_pack_View_eStatement_SIT
#eStatements可以正常查看
  Scenario:Successfully displayed eStatement data
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When I click View eStatements Btn
    When I click select box
      |select       |
      |11010003747  |
    And I click search button
    Then I should see Account List


  @sanity_pack_Download_Eadvice_Data_SIT
    #成功下载eadvice数据
  Scenario:EAdivce can be downloaded normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When I click View eAdvices Btn
    When I click select button on the View eAdvices page
    When I click first data to download on the view eAdvices page


    @sanity_pack_My_Transactions_Query_Success_SIT
    #My Transactions查询交易成功
  Scenario: My Transactions query transaction succeeded
  Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Successful presentation of transaction history

    @sanity_pack_Manage_Alert/Notification_Query_Normally_SIT
    #Manage alert/notification可以正常查询
  Scenario: Manage alert/notification can query normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Successfully demonstrated Bank Announcement

    @sanity_pack_Templete_Download_Normally_SIT
    #templete可以正常下载
  Scenario: Templete can be downloaded normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When Templete can be downloaded normally


    @sanity_pack_Jump_To_SCF_SIT
    #jump to SCF
  Scenario: jump to SCF
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When jump to SCF

    @sanity_pack_Add_Single_Currency_SIT
    #新增单个币种正流程
  Scenario:Add single currency is a positive process
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When I click account Opening
      |CA             |
      |Current Account|
    And I choose the currency to open the account SGD
    When I select account permissions
    When Vkey authorization for Payment transactions in the SIT environment


    @sanity_pack_Add_MCA_Currency_SIT
    #  MCA账户,默认选择SGD，SGD+USD开立
  Scenario:Add multi-currency positive process
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When I click account Opening
      |CA                     |
      |'Multi-Currency Account|
    And  I choose the currency to open USD
    When I select account permissions
    When Vkey authorization for Payment transactions in the SIT environment

    @sanity_pack_Payment_Add_New_Payee_SIT
    #Payment add a new payee
  Scenario:Add a new payee click modify to modify successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Add a new payee in Payees
      |payee bank           |
      |BANK OF CHINA LIMITED|
    When Vkey authorization for Payment transactions in the SIT environment
    Then Add successfully and click modify to modify successfully
    When Vkey authorization for Payment transactions in the SIT environment


    @sanity_pack_Payment_Payees_Delete_SIT
    #Payment payees delete
  Scenario:Add a new payee click delete to delete successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Add a new payee in Payees
      |payee bank           |
      |BANK OF CHINA LIMITED|
    When Vkey authorization for Payment transactions in the SIT environment
    When Delete new payees data
    When Vkey authorization for Payment transactions in the SIT environment

  @sanity_pack_Payment_Modify&Transfer_Payee_SIT
    #Payment modify payee and transfer
  Scenario:Modify payee and Transfer successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Add a new payee in Payees
      |payee bank           |
      |BANK OF CHINA LIMITED|
    When Vkey authorization for Payment transactions in the SIT environment
    Then Add successfully and click modify to modify successfully
    When Vkey authorization for Payment transactions in the SIT environment
    When Click the transfer button on the page to jump to the transfer page
    When Enter information on the transfer details page
      |Payee's Bank           |Payee's Account Number|Purpose of Transfer |From Account  |Payment Type|PayNow Type|PayNow Content|
      |BANK OF CHINA LIMITED  |11552636365           |Business Expenses   |1101 0002 414 |FAST        |VPA        |UEN123321001  |
    When I click next button on the domestic transfer bank page
    Then I verify the information on the next page
    When I click Next to go to the verification page
    When If the transfer failure window pops up I will click the continue button
    When Vkey authorization for Payment transactions in the SIT environment

  @sanity_pack_Payment_Transfer_Payee_SIT
  #Payment transfer payee
  Scenario:Transfer payee successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Click the Transfer button on the page
    When Enter information on the transfer details page
      |Payee's Bank           |Payee's Account Number|Purpose of Transfer |From Account  |Payment Type|PayNow Type|PayNow Content|
      |BANK OF CHINA LIMITED  |11552636365           |Business Expenses   |1101 0002 414 |FAST        |VPA        |UEN123321001  |
    When I click next button on the domestic transfer bank page
    Then I verify the information on the next page
    When I click Next to go to the verification page
    When If the transfer failure window pops up I will click the continue button
    When Vkey authorization for Payment transactions in the SIT environment

  @sanity_pack_PayNow_Signing_Process_Transfer_SIT
      #PayNow签约+Paynow转账
  Scenario:PayNow Signing Process and Transfer
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I execute manage PayNow Profile transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment
    When I got PayNow Proxy ID in the signing details
    When Use the PayNow Proxy ID after successful signing to transfer Paynow
     |Purpose of Transfer |From Account  |Payment Type|PayNow Type|
     |Business Expenses   |1101 0002 414 |PayNow      |UEN        |
    When I click next button on the domestic transfer bank page
    Then I verify the information on the next page
    When I click Next to go to the verification page
    When If the transfer failure window pops up I will click the continue button
    When Vkey authorization for Payment transactions in the SIT environment

  @sanity_pack_Paynow_Profile_Edit_Transfer_SIT
      #PayNow签约+Paynow Profile Edit转账
  Scenario:PayNow Profile Edit Transfer
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I edit manage PayNow Profile transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment
    When I got PayNow Proxy ID in the signing details
    When Use the PayNow Proxy ID after successful signing to transfer Paynow
      |Purpose of Transfer |From Account  |Payment Type|PayNow Type|
      |Business Expenses   |1101 0002 414 |PayNow      |UEN        |
    When I click next button on the domestic transfer bank page
    Then I verify the information on the next page
    When I click Next to go to the verification page
    When If the transfer failure window pops up I will click the continue button
    When Vkey authorization for Payment transactions in the SIT environment

   @sanity_pack_PayNow_Signing_Process_SIT
      #PayNow签约
  Scenario:PayNow Signing Process
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I execute manage PayNow Profile transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment

    @sanity_pack_PayNow_Signing_Off_SIT
   #PayNow解约
  Scenario:PayNow Signing Off
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I sign and cancel the transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment

   @sanity_pack_AppointmentTransferCycleTransferDisplay
   #预约转账/周期转账展示成功
  Scenario: Appointment transfer/cycle transfer display succeeded
     Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
     When Appointment transfer/cycle transfer display succeeded
        |account number|Status of scheduled payments|
        |1102 0327 162 |In Progress                 |

  @sanity_pack_CompanyUserAccountsViewDetails
   #Manage Company Users' Accounts 用户信息，可操作账号，可使用功能展示正确
  Scenario: Manage Company Users Accounts View Details
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Manage Company Users Accounts View Details

  @sanity_pack_ManageCompayAccountCancelTransferAuthority
   #Manage Company's Accounts 取消转账权限
  Scenario: Manage Company's Accounts Cancel transfer authority
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When Manage Company's Accounts Cancel transfer authority
    When Vkey authorization for Payment transactions in the SIT environment
    When Cancellation of verification transfer authority succeeded
      |From Account   |
      |1101 0003 887  |

    #根据账户限额进行转账交易，转出金额大于账户限额 (未完成)
  @Payment_Overseas_Transfer_Amount_Greater_Than_Account_Limit
  Scenario:Make a transfer transaction, and the transferred-out amount is greater than the account limit
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When Make a transfer transaction, and the transferred-out amount is greater than the account limit
      |Account Number|Payment Mode for Charges |
      |1101 0003 747 |SHA                      |
    And I choose the payment currency
      |Currency|
      |SGD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0DOD     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    Then I check error information on the page

  @sanity_pack_Track3_Single_Currency_SGD
    #Track3开户(未完成)
  Scenario:Track3 opened an account with SGD in single currency. The account was opened successfully
    Given open "INB-automation-SIT-login" enterprise net silver page
    When click open Account New page
    Then New Fill in information "netSilverEnv_OpenAccount" on Getting Started page
    And Provide Essential Information New
      |Entity's Type                                  |Entity Consolidated       |Entity's Industry|date      |chekk      |
      |Public Listed Company (Not Listed in Singapore)|Turnover <= SGD 1 Million |Manufacturing    |01/01/2010|2009117799 |
    Given logon "environments_5" on tube by inputting system online bank
    When I into the rear tube Supplementary account opening information

  @sanity_pack_Track1_Single_Currency_SGD
    #Track1开户(未完成)
  Scenario:Myinfo opened an account with SGD in single currency, and the account was opened successfully
    Given open "INB-automation-SIT-login" enterprise net silver page
    When I enter the myinfo page and complete Step 1 information input
      |currency|
      |SGD     |
    When I open the myinfo Mock and get the bezel information
      |url|
      |SIT|
    When I enter information in Step 3 and jump to the next step
    When I enter information in Step 4 and jump to the next step
    When I enter information in Step 5 and jump to the next step
    When I enter information in Step 6 and jump to the next step
    When I enter information in Step 7 and jump to the next step
    When I enter information in Step 8 and jump to the next step
    When I enter information in Step 9 and jump to the next step

  @sanity_pack_Track2_Single_Currency_SGD
    #注册国家选择新加坡企业，客户网银在线开户成功（正常客户）（未完成）
  Scenario:Singapore enterprise was selected as the country of registration, and the online account of the customer's online banking was successfully opened (normal customer).
    Given open "INB-automation-SIT-login" enterprise net silver page
    When click open Account page
    Then Fill in information "netSilverEnv_OpenAccount" on Getting Started page
    And Provide Essential Information
      |Entity's Type                                  |Entity Consolidated       |Entity's Industry|date      |chekk      |
      |Public Listed Company (Not Listed in Singapore)|Turnover <= SGD 1 Million |Manufacturing    |01/01/2010|201328933D |
    Then Enter Connected People's Details
    And Enter Connected Entities’ Details
    Then Create Company Administrators’ Profiles
    And Share Account’s Risk Profile
    Then Upload Supporting Documents
    And Review Details


    @sanity_pack_Check_Account_List_Local_Fund_Transfer_SIT
  #check 账户列表Local fund transfer 可用
    Scenario: Account list SGD query positive process
      Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
      When Query of account list information succeeded

  @sanity_pack_Check_Account_List_Local_Fund_Transfer_Available_SIT
  #check 账户列表Local fund transfer 可用
  Scenario: Check account list Local fund transfer is available
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Check account list Local fund transfer is available


  @sanity_pack_Fixed_Deposits_Overview_Jump_Place_Fixed_Deposit_SIT
  #Fixed Deposits overview跳转Place Fixed Deposit
  Scenario:Fixed Deposits overview jump Place Fixed Deposit
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits First menu
    Then Fixed Deposits overview jump Place Fixed Deposit


  @sanity_pack_Fixed_Deposits_View_Details_SIT
      #Fixed Deposits view details查看详情
  Scenario:Fixed Deposits view details view details
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits First menu
    When Fixed Deposits view details view details

  @sanity_pack_Change_Password_Login_Success_SIT
   #Change Password后可以正常登录
  Scenario:You can log in normally after changing password
    Given logon "INB-automation-SIT-change-password" in SIT environment and change password
    When Click My Settings and select Manage security settings to modify the password
    When Vkey authorization for Payment transactions in the SIT environment
    When I click Confirm Button on the change password page
    When Vkey authorization for Payment transactions in the SIT environment
    Then Password modified successfully check the status
    Given logon "INB-automation-SIT-change-password" in SIT environment and change password

  @sanity_pack_Download_XLS_CSV_XLSX_SIT
    #选择Extract audit logs,分别点击download下的xls格式、csv格式、xlsx格式
  Scenario: Audit logs in three formats were downloaded successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Audit logs in three formats were downloaded successfully
      |transaction type|
      |Login           |

  @sanity_pack_View_Operation_Log_SIT
    #可查看到当前用户和该客户号下其他用户的操作日志
  Scenario: You can view the operation logs of the current user and other users under this customer number
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When You can view the operation logs of the current user and other users under this customer number
      |transaction type|
      |Login           |

  @sanity_pack_Modify_Mobile_Number_SIT
    #修改用户手机号、用户权限，账号权限，用户对网银功能的权限
  Scenario:Modify the user's mobile phone number
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration as well user administration
    When I click modify info menu
      |emailAddress         |
      |bg@263.net           |
    When Vkey authorization for Payment transactions in the SIT environment

  @sanity_pack_Account_List_SGD_Query
#    账户列表SGD查询正流程
  Scenario:Account list SGD query positive process
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When Successful presentation of transaction history

      #操作员有未到期的定期买入(因数据问题，未完成)
  @sanity_pack_Unexpired_Regular_Purchase
  Scenario:The operator has an unexpired regular purchase
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits View menu
    When The operator has an unexpired regular purchase

    #SGD单币种账户买入1个月不转存定期正流程（无授权）
  @sanity_pack_One_Month_fixed_deposit
  Scenario:SGD single-currency account is purchased for one month, and it is not transferred to regular positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits menu
    Then I fill in the information about the SGD transfer on the time deposit page
      |Transfer accounts   |Into account|Amount |Period  |Transfer accounts way|
      |1101 0000 470       |11010000438 |250000 |1 Month |1                    |


      #客户有未授权的交易，My Task授权成功
  @sanity_pack_My_Task_Authorized_Success
  Scenario:My Task authorized successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits menu
    Then I fill in the information about the USD transfer on the time deposit page
      |Transfer accounts   |Into account|Amount |Period   |Transfer accounts way|
      |1101 0000 489       |11010000608 |10000  |18 Months|3                    |
    When logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When Click My Task to find data for authorization

      @sanity_pack_Authorization_Mode_Single
#  授权模式单人
  Scenario:Modify the authorization mode of non-management transactions in enterprises
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When click authorization
    When I choose single-player license management mode
    And Confirm the authorization mode and submit it
    When secondary authorized person notification is then displayed
    Then TC code is then required for Vkey authentication
    When I get the TC code and click Next
    When I typed TC Code and click Authenticate Now
    Then I verify that the transaction is successful


  @sanity_pack_Loan_Application_Product_Overdraft
  Scenario:Enterprise turnover (SGD): The loan application for the product Overdraft was successful
#     活期透支
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I hover over the loan business
    When I choose a turnover of one million to two million
      |amount|
      |200000|
    When I select real estate mortgage
      |houseAddress|zipCode|constructionArea|
      |test123     |123456 |140             |
    When I select personal guarantor
      |name   |birthday  |idCard   |phoneNum   |email           |experience|
      |WANG WU|1988-02-02|S1472581A|13087544979|126161178@qq.com|4         |
    When I fill out other financial commitments on real estate mortgage
      |financialInstitutionName |loanAmt |outstandingAmt |monthlyInstallments |rate|
      |test123                  |12      |1              |0                   |1   |
    When I upload the five required documents
    When I click next button on the upLoadFile page


    #    还款。
  @sanity_pack_Loan_Repayment
  Scenario:For the accounts receivable financing products, the repayment date is five days after the current date, and within one month, before the maturity date, all of them are settled in advance (loan currency: SGD, product term: 30 days), and the repayment is successful
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click the loan Manage ment Button
    When I click SGD Prepay button


    #    贷款支用。无授权
  @sanity_pack_Loan_Drawdown
  Scenario:Positive process of application for disbursement of accounts receivable financing loan (withdrawal currency is SGD, and no review is required)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click the loan draw button
    When I choose a product type to fill in the information
      |product type         |
      |Receivable Financing |
#    When I choose to apply for disbursement of financing receivables
    When I choose Singapore Dollar
    When I have filled in the other information
      |amount|dayNum|goodsDescr|
      |100   |30    |testAnd12 |
    Then TC code is then required for Vkey authentication
    When I get the TC code and click Next
    When I typed TC Code and click Authenticate Now
