@Sanity_Pack_INB_SIT

Feature: Sanity Pack INB SIT Test Case

 #境外转账
  Scenario:Overseas fund transfer SGD-USD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges|
      |1101 0002 414 |SHA                     |
    And I choose the payment currency
      |Currency|
      |USD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment
      |WordPath           |
      |Bic is DBS SGD-USD |
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button
      |search content           |windows Title        |WordPath           |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-USD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page
      |windows Title                            |WordPath           |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS SGD-USD |
    Then I do field mapping for Channel and T24 in FX Payment
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I compare the amount is normal
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I compare the data generated by Outgoing Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-USD|Bic is DBS SGD-USD|
    When I type FOREX in the search box use to authorize the operation
      |search content|user Authorize                 |Name              |
      |FOREX         |T24-automation-SIT-login-Auth  |Bic is DBS SGD-USD|
    When I view the exchange rate in the Payment Order RFQ Rate Audit menu On Oversea Payment MX
      |WordPath          |
      |Bic is DBS SGD-USD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS SGD-USD |

  Scenario:Overseas fund transfer USD-SGD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0000 489 |SHA                      |
    And I choose the payment currency
      |Currency|
      |SGD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment Different Currency MX Message
      |WordPath          |
      |Bic is DBS USD-SGD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Different Currency
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-SGD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page for Different Currency
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-SGD|
    Then I do field mapping for Channel and T24 in FX Payment for Different Currency
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I compare the amount is normal for Different Currency
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I compare the data generated by Outgoing Message is correct for Different Currency
      |WordPath          |Name              |
      |Bic is DBS USD-SGD|Bic is DBS USD-SGD|
    When I type FOREX in the search box use to authorize the operation for Different Currency
      |search content|user Authorize                 |Name              |
      |FOREX         |T24-automation-SIT-login-Auth  |Bic is DBS USD-SGD|
    When I view the exchange rate in the Payment Order RFQ Rate Audit menu On Oversea Payment MX
      |WordPath          |
      |Bic is DBS USD-SGD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS USD-SGD |


  Scenario:Overseas fund transfer SGD-SGD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0002 414 |SHA                      |
    And I choose the payment currency
      |Currency|
      |SGD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment MX Message
      |WordPath          |
      |Bic is DBS SGD-SGD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS SGD-SGD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS SGD-SGD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS SGD-SGD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS SGD-SGD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-SGD|Bic is DBS SGD-SGD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS SGD-SGD |


  Scenario:Overseas fund transfer USD-USD
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on overseas transfer payment and select the account
    When I select the payment account, enter the payment currency and the payment amount and the cost commitment
      |Account Number|Payment Mode for Charges |
      |1101 0000 489 |SHA                      |
    And I choose the payment currency
      |Currency|
      |USD     |
    When I enter the payee information
      |Payee's Account Number|Payee's Name|
      |667812798             |lucky       |
#    When I click on the receiving bank drop down box
    When I choose the receiving bank
      |Beneficiary Bank|
      |DBSSSGS0LAO     |
    When I choose the recipient country
      |Payee's Address |Payee's Country|Comments For Payee|
      |countries       |UNITED STATES  |ok                |
    When I choose the nature of payment
      |Purpose of Transfer|
      |Commission         |
    When I choose to submit the transfer information
    When Vkey authorization for Payment transactions in the SIT environment
    Then I will compare all the data on FX Payment MX Message
      |WordPath          |
      |Bic is DBS USD-USD|
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath          |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Bic is DBS USD-USD|
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath          |
      |Pending and Processed Payments - SIT GLDB|Bic is DBS USD-USD|
    Then I do field mapping for Channel and T24 in same currency
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the amount is normal on Mx Message
      |WordPath          |
      |Bic is DBS USD-USD|
    When I compare the data generated by Outgoing Message MX Message is correct
      |WordPath          |Name              |
      |Bic is DBS SGD-SGD|Bic is DBS USD-USD|
    When I check the deduction amount on the Find Account page On overseas transfer Payment
      |windows Title            |WordPath           |
      |AA Arrangement - SIT GLDB|Bic is DBS USD-USD |

  Scenario:FAST transfer method, new currency to new currency positive process (unauthorized transfer)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Fast         |No                |Weekly   |


  Scenario:FAST transfer method, where the new currency is transferred to the new currency in a positive process (without authorization).
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Fast         |Yes               |Weekly   |

  Scenario:FAST transfer method, new currency to new currency positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|Fast         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:FAST transfer method, the new currency to new currency positive process (without authorization) choose GLDB Bank
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name                      |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |GREEN LINK DIGITAL BANK PTE LTD|Fast         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:MEPS transfer method, new currency to new currency positive process (unauthorized transfer)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Meps         |No                |Weekly   |


  Scenario:MEPS transfer method, where the new currency is transferred to the new currency in a positive process (without authorization).
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date      |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|15/03/2024|BANK OF CHINA LIMITED|Meps         |Yes               |Weekly   |

  Scenario:MEPS transfer method, new currency to new currency positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|Meps         |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:UEN the process of converting new currency to new currency (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content|recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |UEN          |UEN123321001  |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:VPA the process of converting new currency to new currency (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content         |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |VPA          |UEN12345678901DD#GRAB  |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:Mobile the process of converting new currency to new currency (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |Mobile       |90688461       |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

  Scenario:NRIC the process of converting new currency to new currency (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    Then Domestic transfer Fast transfer succeeded and the transaction email was received
      |from account|to account |date    |bank name            |transfer type|PayNow Module|PayNow Content |recurring transfer|date type|
      |11010002414 |11552636365|today   |BANK OF CHINA LIMITED|PayNow       |NRIC         |S1234569B      |No                |Weekly   |
    Then I get transaction details on the page
    Given to verify transaction in T24 using "T24-automation-SIT-login"
    When I type in the content and click the search button on Mx Message
      |search content           |windows Title        |WordPath                   |
      |ENQ ST.API.ITF.GLDB.2.0.0|ST.API.ITF.GLDB.2.0.0|Local Fund Payment SGD-SGD |
    When I expand the User Menu menu on the page
    When I expand the User Payments menu on the page
    When I expand the Payment Hub menu on the page
    When I expand the Payment Inquiries and Exceptions menu on the page
    When I expand the Payments Enquiry Transaction wise menu on the page
    When I jump to a newly opened page on Mx Message
      |windows Title                            |WordPath                   |
      |Pending and Processed Payments - SIT GLDB|Local Fund Payment SGD-SGD |
    When I check the deduction amount on the Find Account page On smock test
      |windows Title            |WordPath                   |
      |AA Arrangement - SIT GLDB|Local Fund Payment SGD-SGD |

     #本人互转
  @localPaymentSGDToSGD
  Scenario:Local Payment Data Mapping FX Payment (SGD->SGD)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I fill in the transfer information on the page
      |From Account |To Account   |
      |11010002414  |11010002430  |
    Then I checked the transfer success in My transactions

# SGD单币种账户买入1个月不转存定期正流程（无授权）
  Scenario:SGD single-currency account is purchased for one month, and it is not transferred to regular positive process (without authorization)
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits menu
    Then I fill in the information about the SGD transfer on the time deposit page
      |Transfer accounts   |Into account|Amount |Period  |Transfer accounts way|
      |1101 0000 470       |11010000438 |250000 |1 Month |1                    |
    Given to verify transaction in T24 using "T24-automation-SIT-login"

#成功展示eStatement数据
  Scenario:Successfully displayed eStatement data
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When I click View eStatements Btn
    When I click select box
      |select       |
      |11010003747  |
    And I click search button
    Then I should see Account List

    #成功下载eadvice数据
  Scenario:EAdivce can be downloaded normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When I click View eAdvices Btn
    When I click select button on the View eAdvices page
    When I click first data to download on the view eAdvices page

  Scenario: My Transactions query transaction succeeded
  Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Successful presentation of transaction history

  Scenario: Manage alert/notification can query normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Successfully demonstrated Bank Announcement

  Scenario: Templete can be downloaded normally
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click My Downloads Btn
    When Templete can be downloaded normally

  Scenario: INB to SCF
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When jump to SCF

    #    CA账户SGD开立
  Scenario:Add single currency is a positive process
    Given logon "INB-automation-SIT-login2" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When I click account Opening
      |CA             |
      |Current Account|
    And I choose the currency to open the account SGD
    When I select account permissions
    When Vkey authorization for Payment transactions in the SIT environment

    #  MCA账户,默认选择SGD，SGD+USD开立
  Scenario:Add multi-currency positive process
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration Desk and select Account Management
    When I click account Opening
      |CA                     |
      |'Multi-Currency Account|
    And  I choose the currency to open USD
    When I select account permissions
    When Vkey authorization for Payment transactions in the SIT environment

    #Payment add a new payee
  Scenario:Add a new payee click modify to modify successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Add a new payee in Payees
      |payee bank           |
      |BANK OF CHINA LIMITED|
    When Vkey authorization for Payment transactions in the SIT environment
    Then Add successfully and click modify to modify successfully
    When Vkey authorization for Payment transactions in the SIT environment

    #Payment payees delete
  Scenario:Add a new payee click delete to delete successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Select Payments and click manage payments
    When Add a new payee in Payees
      |payee bank           |
      |BANK OF CHINA LIMITED|
    When Vkey authorization for Payment transactions in the SIT environment
    When Delete new payees data
    When Vkey authorization for Payment transactions in the SIT environment

      #PayNow签约
  Scenario:PayNow Signing Process
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I execute manage PayNow Profile transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment

   #PayNow解约
  Scenario:PayNow Signing Off
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I sign and cancel the transaction on the page
    When Vkey authorization for Payment transactions in the SIT environment

  #check 账户列表Local fund transfer 可用
    Scenario: Account list SGD query positive process
      Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
      When Query of account list information succeeded

  #check 账户列表Local fund transfer 可用
  Scenario: Check account list Local fund transfer is available
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Check account list Local fund transfer is available

  #Fixed Deposits overview跳转Place Fixed Deposit
  Scenario:Fixed Deposits overview jump Place Fixed Deposit
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits First menu
    Then Fixed Deposits overview jump Place Fixed Deposit

      #Fixed Deposits view details查看详情
  Scenario:Fixed Deposits view details view details
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When click Fixed Deposits First menu
    When Fixed Deposits view details view details

   #Change Password后可以正常登录
  Scenario:You can log in normally after changing password
    Given logon "INB-automation-SIT-change-password" in SIT environment and change password
    When Click My Settings and select Manage security settings to modify the password
    When Vkey authorization for Payment transactions in the SIT environment
    When I click Confirm Button on the change password page
    When Vkey authorization for Payment transactions in the SIT environment
    Then Password modified successfully check the status
    Given logon "INB-automation-SIT-change-password" in SIT environment and change password

    #选择Extract audit logs,分别点击download下的xls格式、csv格式、xlsx格式
  Scenario: Audit logs in three formats were downloaded successfully
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When Audit logs in three formats were downloaded successfully
      |transaction type|
      |Login           |

    #可查看到当前用户和该客户号下其他用户的操作日志
  Scenario: You can view the operation logs of the current user and other users under this customer number
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When You can view the operation logs of the current user and other users under this customer number
      |transaction type|
      |Login           |

    #修改用户手机号、用户权限，账号权限，用户对网银功能的权限
  Scenario:Modify the user's mobile phone number
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When I click on the Enterprise Administration as well user administration
    When I click modify info menu
      |emailAddress         |
      |bg@263.net           |
    When Vkey authorization for Payment transactions in the SIT environment

  Scenario: jump to SCF
    Given logon "INB-automation-SIT-login" in SIT environment and bypass Vkey
    When jump to SCF